UNSAFE_LABELS = {
    "MALE_GENITALIA_EXPOSED" : 0.2,
    "FEMALE_GENITALIA_EXPOSED" : 0.2, 
    "FEMALE_BREAST_EXPOSED" : 0.3, 
    "ANUS_EXPOSED" : 0.2,  
    "ANUS_COVERED" : 0.2,
    "BUTTOCKS_EXPOSED" : 0.2, 
    "FEMALE_GENITALIA_COVERED" : 0.2,  
    "EXPOSED_ANUS" : 0.2, 
}